version: '3.4'

services:
  db-rating-and-review:
    container_name: RatingAndReviewPostgre
    image: postgres:latest
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root