services:
  db-rating-and-review:
    container_name: RatingAndReviewPostgre
    image: postgres:latest
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root

  # rabbitmq:
  #   container_name: MoviesAndShowsCatalogRabbitMQ
  #   image: rabbitmq:3-management   
  #   hostname: RabbitMQ
  #   ports: 
  #       - 5672:5672
  #       - 15672:15672