// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesAndShowsCatalog.MovieAndShow.Infrastructure.Data;

#nullable disable

namespace MoviesAndShowsCatalog.MovieAndShow.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240304014124_SeedVisualProduction")]
    partial class SeedVisualProduction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesAndShowsCatalog.MovieAndShow.Domain.Entities.VisualProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VisualProductions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = 0,
                            ReleaseYear = 2019,
                            Title = "The Witcher"
                        },
                        new
                        {
                            Id = 2,
                            Genre = 0,
                            ReleaseYear = 2014,
                            Title = "John Wick"
                        },
                        new
                        {
                            Id = 3,
                            Genre = 1,
                            ReleaseYear = 2006,
                            Title = "Click"
                        },
                        new
                        {
                            Id = 4,
                            Genre = 1,
                            ReleaseYear = 2010,
                            Title = "Grown Ups"
                        },
                        new
                        {
                            Id = 5,
                            Genre = 2,
                            ReleaseYear = 2008,
                            Title = "Breaking Bad"
                        },
                        new
                        {
                            Id = 6,
                            Genre = 2,
                            ReleaseYear = 2011,
                            Title = "Game of Thrones"
                        },
                        new
                        {
                            Id = 7,
                            Genre = 3,
                            ReleaseYear = 1999,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 8,
                            Genre = 3,
                            ReleaseYear = 2011,
                            Title = "Black Mirror"
                        },
                        new
                        {
                            Id = 9,
                            Genre = 4,
                            ReleaseYear = 2021,
                            Title = "Shadow and Bone"
                        },
                        new
                        {
                            Id = 10,
                            Genre = 4,
                            ReleaseYear = 2001,
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = 11,
                            Genre = 5,
                            ReleaseYear = 2005,
                            Title = "Supernatural"
                        },
                        new
                        {
                            Id = 12,
                            Genre = 5,
                            ReleaseYear = 1978,
                            Title = "Halloween"
                        },
                        new
                        {
                            Id = 13,
                            Genre = 6,
                            ReleaseYear = 2010,
                            Title = "Sherlock"
                        },
                        new
                        {
                            Id = 14,
                            Genre = 6,
                            ReleaseYear = 2013,
                            Title = "Prisoners"
                        },
                        new
                        {
                            Id = 15,
                            Genre = 7,
                            ReleaseYear = 2014,
                            Title = "Outlander"
                        },
                        new
                        {
                            Id = 16,
                            Genre = 7,
                            ReleaseYear = 1997,
                            Title = "Titanic"
                        },
                        new
                        {
                            Id = 17,
                            Genre = 8,
                            ReleaseYear = 2020,
                            Title = "The Last Dance"
                        },
                        new
                        {
                            Id = 18,
                            Genre = 8,
                            ReleaseYear = 2012,
                            Title = "The Act of Killing"
                        },
                        new
                        {
                            Id = 19,
                            Genre = 9,
                            ReleaseYear = 1989,
                            Title = "The Simpsons"
                        },
                        new
                        {
                            Id = 20,
                            Genre = 9,
                            ReleaseYear = 2001,
                            Title = "Shrek"
                        },
                        new
                        {
                            Id = 21,
                            Genre = 10,
                            ReleaseYear = 2013,
                            Title = "Vikings"
                        },
                        new
                        {
                            Id = 22,
                            Genre = 10,
                            ReleaseYear = 1981,
                            Title = "Indiana Jones Series"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
