services:
  db-user:
    container_name: UserMySql
    image: mysql:latest
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root

  # rabbitmq:
  #   container_name: MoviesAndShowsCatalogRabbitMQ
  #   image: rabbitmq:3-management   
  #   hostname: RabbitMQ
  #   ports: 
  #       - 5672:5672
  #       - 15672:15672