version: '3.4'

services:
  db-movie-and-show:
    container_name: MovieAndShowSqlServer
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
        - 1433:1433
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: root@strongPassword
        MSSQL_PID: Developer

  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management   
    hostname: RabbitMQ
    restart: always
    ports: 
        - 5672:5672